### ISSUE TITLE
Unity Package Manager [UPM] How to pull an update?

### ISSUE THREAD

**Issue by jasursadikov** [ashblue/unity-package-manager-git-example#1]
Hello, thank you so much for your example. It was really helpful to try new package system.
But, I still do not understand how to push update without removing package and adding it again.
When I push my package with new version changed in file `package.json` I do not receive and Update button in my package manager window.
Could you explain how it works. Thank you.

**Comment by jasursadikov** [comment]
I found a solution
Remove `"lock"` attribute for your package in `manifest.json` and Unity will load last version of your package

**Comment by ashblue** [comment]
Sorry about the delay on getting back (never got a notification for this oddly). Glad to hear you were able to get the version to update. I think you can do the same by going into the GUI package manager interface and clicking update.

**Comment by jasursadikov** [comment]
> Sorry about the delay on getting back (never got a notification for this oddly). Glad to hear you were able to get the version to update. I think you can do the same by going into the GUI package manager interface and clicking update.

Unfortunately GUI manager is not observing remote updates. Seems like, this is the only way.

**Comment by ashblue** [comment]
Ahh right, if you're using a Git based link I forgot it doesn't observe things and locks it based on the hash. I actually wrote [Oyster Package Manager](https://github.com/ashblue/oyster-package-generator) to help solve this problem. I hope they fix that with the GUI soon so you can forcefully update the lock.
